version: '3.1'
services:
  stats-client:
    build: stats/stats-client
    image: stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
      - "5081:5081"
    environment:
      - DEBUG_SERVER_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5081
    depends_on:
      - stats-service
    networks:
      default:
        ipv4_address: 172.16.1.4

  stats-service:
    build: stats/stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9091:9091"
      - "5082:5082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.16.1.6:5432/stats-db
      - DEBUG_SERVER_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5082
    depends_on:
      - stats-db
    networks:
      default:
        ipv4_address: 172.16.1.5


  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
      default:
        ipv4_address: 172.16.1.6

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pass
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - stats-db

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24