version: '3.1'
services:
  stats-client:
    build: stats/stats-client
    image: stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - stats_service_url=http://stats-server:9091
    depends_on:
      - stats-server

  stats-server:
    build: stats/stats-service
    image: stats-service
    container_name: stats-server
    environment:
      - SERVER_PORT=9091
      - SPRING.DATASOURCE.URL=jdbc:postgresql://stats-db:5432/stats-db
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring_kafka_bootstrap_servers=kafka:9092
    depends_on:
      - stats-db
      - kafka

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  ewm-service:
    build: ewm/ewm-service
    container_name: ewm-service
    environment:
      - SERVER_PORT=8081
      - SPRING.DATASOURCE.URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - stats_client_url=http://stats-client:9090
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring_kafka_bootstrap_servers=kafka:9092
      - spring_kafka_consumer_group-id=ewmGroup
    depends_on:
      - ewm-db
      - kafka

  ewm-client:
    build: ewm/ewm-client
    container_name: ewm-client
    environment:
      - SERVER_PORT=8080
      - ewm_service_url=http://ewm-service:8081
      - stats_client_url=http://stats-client:9090
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service

  ewm-db:
    image: postgres:14-alpine
    restart: always
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1