version: '3.1'
services:
  stats-client:
    build: stats/stats-client
    image: stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
    environment:
      - stats-service.url=http://stats-service:9091
    depends_on:
      - stats-service
    networks:
      default:

  stats-service:
    build: stats/stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9091:9091"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://stats-db:5432/stats-db
    depends_on:
      - stats-db
    networks:
      default:

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
     default:

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine

networks:
  default: