version: '3.1'
services:
  stats-client:
    build: stats/stats-client
    image: stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
      - "5081:5081"
    environment:
      - TZ=Europe/Moscow
      - stats_service_url=http://stats-server:9091
      - DEBUG_SERVER_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5081
    depends_on:
      - stats-server

  stats-server:
    build: stats/stats-service
    image: stats-service
    container_name: stats-server
    ports:
      - "9091:9091"
      - "5082:5082"
    environment:
      - TZ=Europe/Moscow
      - SPRING.DATASOURCE.URL=jdbc:postgresql://stats-db:5432/stats-db
      - DEBUG_SERVER_JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5082
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=stats-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pass
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - stats-db