apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewm-service-deployment
  labels:
    app: ewm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ewm-service
  template:
    metadata:
      labels:
        app: ewm-service
    spec:
      containers:
        - name: ewm-service
          image: glazyrinalexey/java-explore-with-me-ewm-service:ewm-service
          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ewm-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ewm-db-secret
                  key: password
            - name: EWM_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ewm-db-config
                  key: ewm-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: ewm-service-service
spec:
  selector:
    app: ewm-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081