apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service-deployment
  labels:
    app: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          image: glazyrinalexey/stats-service:stats-service
          ports:
            - containerPort: 9091
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: stats-db-secret
                  key: spring.datasource.username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stats-db-secret
                  key: spring.datasource.password
            - name: STATS_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: stats-db-config
                  key: stats-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service-service
spec:
  selector:
    app: stats-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091