apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ewm-db-deployment
  labels:
    app: ewm-db
spec:
  replicas: {{ .Values.ewm.replicaCount }}
  selector:
    matchLabels:
      app: ewm-db
  template:
    metadata:
      labels:
        app: ewm-db
    spec:
      containers:
        - name: stats-db
          image: {{ .Values.ewm.dbImage }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ewm-db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ewm-db-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ewm-db-secret
                  key: dbname
---
apiVersion: v1
kind: Service
metadata:
  name: ewm-db
spec:
  selector:
    app: ewm-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432