apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-kafka-broker-deployment
  labels:
    app: kafka-broker
spec:
  replicas: {{.Values.kafka.replicaCount}}
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - name: kafka-broker
          image: {{.Values.kafka.kafkaImage}}
          ports:
            - containerPort: 9092
          env:
          - name: KAFKA_BROKER_ID
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_BROKER_ID
          - name: KAFKA_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_ZOOKEEPER_CONNECT
          - name: KAFKA_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_LISTENERS
          - name: KAFKA_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: kafka-config
                key: KAFKA_ADVERTISED_LISTENERS
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker