apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-zookeeper-service-deployment
  labels:
    app: zookeeper-service
spec:
  replicas: {{.Values.kafka.replicaCount}}
  selector:
    matchLabels:
      app: zookeeper-service
  template:
    metadata:
      labels:
        app: zookeeper-service
    spec:
      containers:
        - name: zookeeper-service
          image: {{.Values.kafka.zookeeperImage}}
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper-service
  type: NodePort
  ports:
      - port: 2181
        nodePort: 30181
        targetPort: 2181